name: Chris Crawford
favicon: null
layout_spectrum: 0.95727
typography_spectrum: 0
title: 'Chris Crawford Founder of Kick Ass Media, Speaker and Coach.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262624'
    - '#a94116'
    - '#a6191f'
    - '#1b6e96'
    - '#ffca46'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
