name: Chris Crawford
favicon: null
layout_spectrum: 0.7039346697274595
typography_spectrum: 0.06969308946281672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5848228137474507
  lightness: 0.22241132310591638
  saturation: 0.0207147472538054
  rhythmicContrast: 0.42598168971017003
purpose: []
